### ISSUE TITLE
Values set via mapPropsToFields are not present when the form is submitted

### ISSUE THREAD

**Issue by deliriousrhino** [react-component/form#137]
Values set via mapPropsToFields are not present when the form is submitted if a getFieldDecorator is not used.

This creates problems if values fields are hidden by the UI

See 
https://github.com/deliriousrhino/rc-form-values-example

**Comment by bencallaway** [comment]
I've also run into this scenario. As a relative newcomer to the library (via antd), I would expect `mapPropsToFields` to be responsible for setting the form store's field meta data before I would expect `getFieldDecorator` to so (by calling `getFieldProps`which calls `fieldsStore.setFieldMeta`). I've gotten the desired effect of binding a "hidden" field by calling `getFieldProps`, but I have to add comments to the code in order to make the intent clear. Is there a better way to register a field in the underlying story that I've overlooked?

If we're not overlooking something then I think it could be useful to either have `mapPropsToFields` set the form store's field meta data, or – if that would interfere with other ways that field meta data is set or expected to be set – have an explicit method/option for setting hidden fields.

Without much appreciation (yet) for the internals for `createForm` it seems like the first option of adding the field setting behavior to `mapPropsToFields` is more intuitive – to "map" something seems more like a mutating event than to "get" something. What do you all think? I'm willing to put a PR together if you think it is a feature worth pursuing

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/NdQdBw?editors=0011

**Comment by benjycui** [comment]
Close for no response.
